---
experiments:
  metero_use: ['t2m',
               'crwc',
               't',
               'u',
               'v',]
  pred_var: ['t']
  save_npy: True
  dataset_num: 1
  # model: LS_GNN
  model: IDGL

train:
  epochs: 50
  exp_repeat: 10
  batch_size: 50
  hist_len: 24
  pred_len: 24
  weight_decay: 0.0005
  early_stop: 10
  lr: 0.0005
  optimizer: rmsprop
  lr_patience: 2
  lr_reduce_factor: 0.5
  batch_epoch: 3

filepath:
  #Your machine name: filepath


data:
#  metero_var: ['d2m',
#               't2m',
#               'skt',
#               'stl1',
#               'sp',
#               'tp',]
  metero_var: [ 'ciwc',
                'clwc',
                'q',
                'crwc',
                't',
                'u',
                'v', ]

dataset:
  data_start: [[2018, 1, 1, 0, 0], GMT]
#  data_end: [[2022, 12, 30, 21, 0], GMT]
  data_end: [[2022, 11, 29, 21, 0], GMT]
  start_month: 1
  end_month: 12

# 2021_6-8 class
  1:
    train_start: [ [ 2018, 1, 1, 0, 0 ], GMT ]
    train_end: [ [ 2020, 12, 12, 3, 0 ], GMT ]
    val_start: [ [ 2020, 12, 12, 6, 0 ], GMT ]
    val_end: [ [ 2021, 12, 30, 18, 0 ], GMT ]
    test_start: [ [ 2022, 6, 1, 3, 0 ], GMT ]
    test_end: [ [ 2022, 8, 31, 21, 0 ], GMT ]

idgl:
  seed: 38
  hidden_size: 5 #改feature数量需要改 5
  graph_learn: True # False True
  physics_guidance: False # True
  graph_skip_conn: 0.8
  graph_include_self: False
  graph_model: ls-gnn # agrcn # ls-gnn # dcrnn # stgcn # clcrn
  graph_learn_num_pers: 4
  graph_metric_type: 'weighted_cosine'
  graph_learn_topk: null
  graph_learn_epsilon: 0
  graph_learn_hidden_size: 70
  graph_learn_regularization: True
  patience: 100
  max_epochs: 1000
  verbose: 20
  dropout: 0.5
  feat_adj_dropout: 0.5 # 0.5
  gl_dropout: 0.8
  print_every_epochs: 500 # Print every X epochs
  max_iter: 15 # gl max epoches
  smoothness_ratio: 0.2
  degree_ratio: 0
  sparsity_ratio: 0
  eps_adj: 4e-5
  update_adj_ratio: 0.1

agcrn:
  input_dim: 1
  output_dim: 1
  embed_dim: 10
  rnn_units: 64
  num_layers: 2
  cheb_order: 2 # 切比雪夫项数 Chebyshev term number
  node_num: 142

dcrnn:
  cl_decay_steps: 1000
  use_curriculum_learning: False
  input_dim: 1
  output_dim: 1
  max_diffusion_step: 2
  filter_type: random_walk
  num_nodes: 142
  num_rnn_layers: 2
  rnn_units: 64

stgcn:
  Kt: 2
  Ks: 3
  stblock_num: 1
  act_func: glu
  graph_conv_type: graph_conv
  gso_type: sym_norm_lap
  enable_bias: True
  droprate: 0.5
  n_vertex: 142

clcrn:
  max_view: 2
  cl_decay_steps: 1000
  node_num: 142
  layer_num: 2
  rnn_units: 32
  input_dim: 1
  output_dim: 1
  embed_dim: 16
  location_dim: 2
  hidden_units: 16
  block_num: 2
  use_curriculum_learning: False

